### ISSUE TITLE
Change MainPage.xaml for WindowsPhone templates

### ISSUE THREAD

**Issue by asudbury** [asudbury/NinjaCoderForMvvmCross#166]
Cahnge MainPage.xaml to have a build action of page and the MainPage.xaml.cs to have a build action of compile

**Comment by asudbury** [comment]
private download available here with the changes

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderForMvxXamarinFormsInstaller.msi

**Comment by MobiliTips** [comment]
Back to dev life and just tried last version:
* iOS ok :)
* WinPhone ok :)
* Droid: SplashScreen files still left. Wonder why as I can see both included into the MvvmCross nuspec file... When both files manualy added, droid works great to :)
* Forms: We should add <Label Text="{Binding SampleText}" HorizontalOptions="Center" VerticalOptions="Center"></Label> into the content view of the MainView.xaml so that we could launch app directly after creation.

Never been so close to our goal!
(We can close the Windows Phone issue as it works great now)

**Comment by MobiliTips** [comment]
Ok I get it for Droid:
You have to target the Scorchio.NinjaCoder.MvvmCross.1.0.1 nuget package to Xamarin.iOS10 and MonoAndroid as it contains droid splash screen files.
For now it only target Xamarin.iOS10.

**Comment by asudbury** [comment]
Thanks close the current and create a new one - will take a look later if you don't beat me to it :-)
