### ISSUE TITLE
NC always creates the standard MvvmCross project

### ISSUE THREAD

**Issue by jsbeckr** [asudbury/NinjaCoderForMvvmCross#219]
Hey,

it seems that NC 4.1 always creates the standard MvvmCross project no matter what you choose in the wizzard (e.g. MvvmCross + Xamarin.Forms).

NinjaReadme.txt below

---
## 23 May 16 22:00 Add Projects

Lökjkj.Core project successfully added. (template NinjaCoder.Core.zip)
Lökjkj.Droid project successfully added. (template NinjaCoder.Droid.zip)

---
## Options

MvvmCross framework selected.
NUnit testing framework selected.
Moq mocking framework selected.
iOS View Type Xib selected.

MainViewModel.cs added to Lökjkj.Core project (template=MvxSampleDataViewModel.t4)
MainView.cs added to Lökjkj.Droid project (template=SampleDataView.t4)

---
## Nuget Commands

Install-Package MvvmCross -FileConflictAction Overwrite -ProjectName Lökjkj.Core 
Install-Package Scorchio.NinjaCoder.MvvmCross.Core -FileConflictAction Overwrite -ProjectName Lökjkj.Core 
Install-Package MvvmCross -FileConflictAction Overwrite -ProjectName Lökjkj.Droid 
Install-Package Scorchio.NinjaCoder.MvvmCross -FileConflictAction ignore -ProjectName Lökjkj.Droid 

---
## Ninja Coder for MvvmCross and Xamarin Forms v4.1.0

All feedback welcome, please get in touch via twitter.

Issues Log http://github.com/asudbury/NinjaCoderForMvvmCross/issues

Thanks

@asudbury

**Comment by asudbury** [comment]
I'm not sure I understand - what options did you select? and what did projects were created (that you didn't want!)

**Comment by jsbeckr** [comment]
I selected MvvmCross + Forms and NC created the standard MvvmCross project with AXML layouts instead of XAML Layouts in the Core Project (see log from above). It didn't install any Forms specific nuget packages. I didn't see any errors. 

I'm giving a workshop right now, so it might take me a while to answer. Sorry. :)

**Comment by asudbury** [comment]
@jsbeckr did you have 'Xamarin Forms' project checkbox selected?

**Comment by asudbury** [comment]
@jsbeckr it suggests from the trace log you selected 'MvvmCross' and not 'MvvmCross and Xamarin Forms'

Options

MvvmCross framework selected.

**Comment by asudbury** [comment]
@jsbeckr can you give me an update on this - I will close unless you report back.

**Comment by florkl** [comment]
Hey,

I have the same problem. It totally doesn't matter whether I check "No Framework", "MvvmCross", "Xamarin Forms" or "MvvmCross and Xamarin Forms" in the "Add Projects" wizard. The created projects are always the same.
Additionally, I discovered that no changes I make in the options dialog are stored. That means I cannot give you a trace or log file since I cannot enable to create them.

**Comment by florkl** [comment]
@jsbeckr hey, yesterday I didn't recognize who you are. We met at a Xamarin workshop at the end of may. Do you also still have this problem or did you find any solution in the meantime?

**Comment by florkl** [comment]
Hey,

it seems that during the NC installation routine, the required registry keys are not added. That's why NC does not consider most of the selections made in the wizard.
I manually added the following registry key: "HKCU.Software.Scorchio Limited.Ninja Coder for MvvmCross". After that I opened the NC settings dialog once, so the standard properties are written to the registry.
This solved the problem for me.

**Comment by Telavian** [comment]
I had the same issue and the workaround from florkl worked for me.

**Comment by asudbury** [comment]
@jsbeckr - see issue 225 will hopefully solve your issue with v4.2.1

@florkl good spot my friend - hopefully v4.2.1 will solve this issue

https://github.com/asudbury/NinjaCoderForMvvmCross/issues/225

**Comment by asudbury** [comment]
Fixed in Version 4.2.1 which is now available on the Visual Studio Market Place.

https://marketplace.visualstudio.com/items?itemName=NinjaCoderforMvvmCross.NinjaCoderForMvvmCrossandXamarinForms
